### ISSUE TITLE
프로젝트 초기 설정 

### ISSUE THREAD

**Issue by DevDAN09** [FUKUO-KA/soongsil-carries-love#1]
# 프로젝트 초기설정
추가하실 라이브러리 있으면 comment 부탁드립니다.

## 상태관리
- Zustand

## 서버 상태 관리 
- React Query

## 네트워크 통신
- Axios

## 스타일
- Styled Components(CSS-in-JS)

**Comment by seocylucky** [comment]
좋슴니다아 pnpm + vite로 설치 하면 좋을 거 같아여
framer는 저희 애니메이션..? 할거면 넣는게 좋을 거 같구 이건 뭐 개발하다가 넣어도 될 거 같습니다~

폴더 구조는 저희
```
└── src
    ├── apis
    ├── assets
    ├── components
     │   └── Card
     |       └── Card.tsx
     |       └── Card.style.ts
    ├── hooks
    ├── pages
    ├── store
    └── types
```

어떠세용

prettier랑 eslint는 제가 할까여
